--- !ruby/object:Claret::Project 
items: 
- !ruby/object:Claret::Task 
  contributes_to: []

  dependents: []

  finish_date: &id001 2008-12-07 17:11:35.811023 -05:00
  id: 1
  name: Create new command line interface
  start_date: *id001
- !ruby/object:Claret::Task 
  contributes_to: []

  dependents: []

  id: 2
  name: put dependent jars under ivy
- !ruby/object:Claret::Task 
  contributes_to: []

  dependents: []

  id: 4
  name: better test cases for better coverage
- !ruby/object:Claret::Task 
  contributes_to: []

  dependents: []

  id: 5
  name: Remove ImportStatement.DEBUG in favor of real logging
- !ruby/object:Claret::Task 
  contributes_to: []

  dependents: []

  id: 6
  name: Allow system properties to override rc file
- !ruby/object:Claret::Task 
  contributes_to: []

  dependents: []

  finish_date: &id002 2008-12-07 17:15:11.997493 -05:00
  id: 7
  name: Rename 'scrubber' to 'scour' wherever appropriate
  start_date: *id002
- !ruby/object:Claret::Task 
  contributes_to: []

  dependents: []

  finish_date: &id003 2008-12-07 19:52:23.264163 -05:00
  id: 8
  name: Create git hook
  start_date: *id003
- !ruby/object:Claret::Task 
  contributes_to: []

  dependents: []

  id: 9
  name: Devise means by which certain files can be skipped
- !ruby/object:Claret::Task 
  contributes_to: []

  dependents: []

  id: 10
  name: Create configuration option to not fail on sources with no classes
- !ruby/object:Claret::Task 
  contributes_to: []

  dependents: []

  id: 11
  name: Create better means of packaging for actual usage
name: Import Scrubber
next_id: 12
