--- !ruby/object:Claret::Project 
items: 
- !ruby/object:Claret::Task 
  contributes_to: []

  dependents: []

  id: 1
  name: Create new command line interface
- !ruby/object:Claret::Task 
  contributes_to: []

  dependents: []

  id: 2
  name: put dependent jars under ivy
- !ruby/object:Claret::Task 
  contributes_to: []

  dependents: []

  id: 3
  name: refactor some filth
- !ruby/object:Claret::Task 
  contributes_to: []

  dependents: []

  id: 4
  name: better test cases for better coverage
- !ruby/object:Claret::Task 
  contributes_to: []

  dependents: []

  id: 5
  name: Remove ImportStatement.DEBUG in favor of real logging
- !ruby/object:Claret::Task 
  contributes_to: []

  dependents: []

  id: 6
  name: Allow system properties to override rc file
- !ruby/object:Claret::Task 
  contributes_to: []

  dependents: []

  id: 7
  name: Rename 'scrubber' to 'scour' wherever appropriate
name: Import Scrubber
next_id: 8
